server:
  port: 8080
  servlet:
    context-path: /web
spring:
  devtools:
    restart:
      poll-interval: 3000ms
  application:
    name: candy
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: oracle
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/adminserver?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
          username: root
          password: a
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
          username: scott
          password: scott
          driver-class-name: oracle.jdbc.driver.OracleDriver
      druid:
        type: com.alibaba.druid.pool.DruidDataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        #validationQuery: select 'x'
        testWhileIdle: false
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: xyz.wsyzz.candy.entity
#pagehelper
pagehelper:
    reasonable: false
    supportMethodsArguments: false
    params: count=countSql
    auto-dialect: true
    auto-runtime-dialect: true
#日志
logging:
  level:
    xyz.wsyzz.candy.mapper: info


