server:
  port: 8080
  servlet:
    context-path: /web
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminserver?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a